workflows:
  expo-eas-build:
    name: Expo Android Build
    max_build_duration: 60
    environment:
      node: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - npm install
      - npm install -g expo-cli eas-cli
      - export EXPO_TOKEN=$EXPO_TOKEN
      - eas build -p android --profile preview --non-interactive
    artifacts:
      - build/**