export const Strings = {
  hi: {
    appName: 'NIKAT',
    tagline: 'Jo chahiye, sab paas',
    hello: 'नमस्ते',
    selectLanguage: 'भाषा चुनें',
    hindi: 'हिंदी',
    english: 'English',
    marathi: 'मराठी',
    home: 'होम',
    categories: 'कैटेगरी',
    kirana: 'किराना',
    electrician: 'इलेक्ट्रीशियन',
    tanker: 'टैंकर',
    food: 'खाना',
    services: 'सर्विसेज',
    emergency: 'इमरजेंसी',
    callShop: 'कॉल करें',
    whatsapp: 'WhatsApp',
    unlockToContact: 'संपर्क के लिए अनलॉक करें',
    phoneNumber: 'फोन नंबर',
    address: 'पता',
    rating: 'रेटिंग',
    distance: 'दूरी',
    noShopsAvailable: 'कोई दुकान उपलब्ध नहीं है',
    addShop: 'दुकान जोड़ें',
    register: 'रजिस्टर करें',
    login: 'लॉगिन करें',
    getOTP: 'OTP प्राप्त करें',
    verifyOTP: 'OTP सत्यापित करें',
    name: 'नाम',
    category: 'कैटेगरी',
    location: 'स्थान',
    continue: 'जारी रखें',
    submit: 'जमा करें',
    selectPlan: 'प्लान चुनें',
    subscribe: 'सदस्यता लें',
    month: 'महीना',
    months: 'महीने',
    price: 'कीमत',
    activeSubscription: 'सक्रिय सदस्यता',
    subscriptionExpired: 'सदस्यता समाप्त हो गई',
    logout: 'लॉगआउट',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    networkError: 'नेटवर्क त्रुटि',
    loading: 'लोड हो रहा है...',
    tryAgain: 'फिर से दोबारा कोशिश करें',
    success: 'सफल',
    error: 'त्रुटि',
  },
  en: {
    appName: 'NIKAT',
    tagline: 'Everything nearby',
    hello: 'Hello',
    selectLanguage: 'Select Language',
    hindi: 'हिंदी',
    english: 'English',
    marathi: 'मराठी',
    home: 'Home',
    categories: 'Categories',
    kirana: 'Grocery',
    electrician: 'Electrician',
    tanker: 'Water Tanker',
    food: 'Food',
    services: 'Services',
    emergency: 'Emergency',
    callShop: 'Call',
    whatsapp: 'WhatsApp',
    unlockToContact: 'Unlock to Contact',
    phoneNumber: 'Phone Number',
    address: 'Address',
    rating: 'Rating',
    distance: 'Distance',
    noShopsAvailable: 'No shops available',
    addShop: 'Add Shop',
    register: 'Register',
    login: 'Login',
    getOTP: 'Get OTP',
    verifyOTP: 'Verify OTP',
    name: 'Name',
    category: 'Category',
    location: 'Location',
    continue: 'Continue',
    submit: 'Submit',
    selectPlan: 'Select Plan',
    subscribe: 'Subscribe',
    month: 'Month',
    months: 'Months',
    price: 'Price',
    activeSubscription: 'Active Subscription',
    subscriptionExpired: 'Subscription Expired',
    logout: 'Logout',
    profile: 'Profile',
    settings: 'Settings',
    networkError: 'Network Error',
    loading: 'Loading...',
    tryAgain: 'Try Again',
    success: 'Success',
    error: 'Error',
  },
  mr: {
    appName: 'NIKAT',
    tagline: 'जे हवेस ते येथे आहे',
    hello: 'नमस्कार',
    selectLanguage: 'भाषा निवडा',
    hindi: 'हिंदी',
    english: 'English',
    marathi: 'मराठी',
    home: 'मुख्य पृष्ठ',
    categories: 'श्रेणी',
    kirana: 'किराणा',
    electrician: 'इलेक्ट्रिशियन',
    tanker: 'टँकर',
    food: 'खाना',
    services: 'सेवा',
    emergency: 'आपत्कालीन',
    callShop: 'कॉल करा',
    whatsapp: 'WhatsApp',
    unlockToContact: 'संपर्क साठी अनलॉक करा',
    phoneNumber: 'फोन नंबर',
    address: 'पता',
    rating: 'रेटिंग',
    distance: 'अंतर',
    noShopsAvailable: 'कोणत्याही दुकान उपलब्ध नाही',
    addShop: 'दुकान जोडा',
    register: 'नोंदणी करा',
    login: 'लॉगिन करा',
    getOTP: 'OTP मिळवा',
    verifyOTP: 'OTP सत्यापित करा',
    name: 'नाव',
    category: 'श्रेणी',
    location: 'स्थान',
    continue: 'सुरू ठेवा',
    submit: 'सबमिट करा',
    selectPlan: 'योजना निवडा',
    subscribe: 'सदस्यता घ्या',
    month: 'महिना',
    months: 'महिने',
    price: 'किंमत',
    activeSubscription: 'सक्रिय सदस्यता',
    subscriptionExpired: 'सदस्यता संपली',
    logout: 'लॉगआउट करा',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्ज',
    networkError: 'नेटवर्क त्रुटी',
    loading: 'लोड होत आहे...',
    tryAgain: 'पुन्हा प्रयत्न करा',
    success: 'यशस्वी',
    error: 'त्रुटी',
  },
};
